/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AuthorityRouteImport } from './routes/authority'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorityOverviewRouteImport } from './routes/authority.overview'
import { Route as AuthorityLoginRouteImport } from './routes/authority.login'
import { Route as AuthorityDashboardRouteImport } from './routes/authority.dashboard'
import { Route as AuthorityComplaintsRouteImport } from './routes/authority.complaints'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityOverviewRoute = AuthorityOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityLoginRoute = AuthorityLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityDashboardRoute = AuthorityDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityComplaintsRoute = AuthorityComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthorityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRouteWithChildren
  '/report': typeof ReportRoute
  '/track': typeof TrackRoute
  '/authority/complaints': typeof AuthorityComplaintsRoute
  '/authority/dashboard': typeof AuthorityDashboardRoute
  '/authority/login': typeof AuthorityLoginRoute
  '/authority/overview': typeof AuthorityOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRouteWithChildren
  '/report': typeof ReportRoute
  '/track': typeof TrackRoute
  '/authority/complaints': typeof AuthorityComplaintsRoute
  '/authority/dashboard': typeof AuthorityDashboardRoute
  '/authority/login': typeof AuthorityLoginRoute
  '/authority/overview': typeof AuthorityOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRouteWithChildren
  '/report': typeof ReportRoute
  '/track': typeof TrackRoute
  '/authority/complaints': typeof AuthorityComplaintsRoute
  '/authority/dashboard': typeof AuthorityDashboardRoute
  '/authority/login': typeof AuthorityLoginRoute
  '/authority/overview': typeof AuthorityOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authority'
    | '/report'
    | '/track'
    | '/authority/complaints'
    | '/authority/dashboard'
    | '/authority/login'
    | '/authority/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authority'
    | '/report'
    | '/track'
    | '/authority/complaints'
    | '/authority/dashboard'
    | '/authority/login'
    | '/authority/overview'
  id:
    | '__root__'
    | '/'
    | '/authority'
    | '/report'
    | '/track'
    | '/authority/complaints'
    | '/authority/dashboard'
    | '/authority/login'
    | '/authority/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorityRoute: typeof AuthorityRouteWithChildren
  ReportRoute: typeof ReportRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/overview': {
      id: '/authority/overview'
      path: '/overview'
      fullPath: '/authority/overview'
      preLoaderRoute: typeof AuthorityOverviewRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/login': {
      id: '/authority/login'
      path: '/login'
      fullPath: '/authority/login'
      preLoaderRoute: typeof AuthorityLoginRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/dashboard': {
      id: '/authority/dashboard'
      path: '/dashboard'
      fullPath: '/authority/dashboard'
      preLoaderRoute: typeof AuthorityDashboardRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/complaints': {
      id: '/authority/complaints'
      path: '/complaints'
      fullPath: '/authority/complaints'
      preLoaderRoute: typeof AuthorityComplaintsRouteImport
      parentRoute: typeof AuthorityRoute
    }
  }
}

interface AuthorityRouteChildren {
  AuthorityComplaintsRoute: typeof AuthorityComplaintsRoute
  AuthorityDashboardRoute: typeof AuthorityDashboardRoute
  AuthorityLoginRoute: typeof AuthorityLoginRoute
  AuthorityOverviewRoute: typeof AuthorityOverviewRoute
}

const AuthorityRouteChildren: AuthorityRouteChildren = {
  AuthorityComplaintsRoute: AuthorityComplaintsRoute,
  AuthorityDashboardRoute: AuthorityDashboardRoute,
  AuthorityLoginRoute: AuthorityLoginRoute,
  AuthorityOverviewRoute: AuthorityOverviewRoute,
}

const AuthorityRouteWithChildren = AuthorityRoute._addFileChildren(
  AuthorityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorityRoute: AuthorityRouteWithChildren,
  ReportRoute: ReportRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
