"""create pipelines table

Revision ID: 3ede0032390d
Revises: a1b2c3d4e5f6
Create Date: 2026-07-17 18:22:34.072300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ede0032390d'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.String(length=50), nullable=False),
    sa.Column('start_latitude', sa.Float(), nullable=False),
    sa.Column('start_longitude', sa.Float(), nullable=False),
    sa.Column('end_latitude', sa.Float(), nullable=False),
    sa.Column('end_longitude', sa.Float(), nullable=False),
    sa.Column('center_latitude', sa.Float(), nullable=False),
    sa.Column('center_longitude', sa.Float(), nullable=False),
    sa.Column('pipe_age_years', sa.Float(), nullable=False),
    sa.Column('material', sa.String(length=50), nullable=False),
    sa.Column('diameter_mm', sa.Float(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('previous_failures', sa.Integer(), nullable=False),
    sa.Column('days_since_last_maintenance', sa.Float(), nullable=False),
    sa.Column('complaints_last_30_days', sa.Integer(), nullable=False),
    sa.Column('leakage_complaints_30d', sa.Integer(), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_pipeline_id'), 'pipelines', ['pipeline_id'], unique=True)
    op.create_index(op.f('ix_pipelines_risk_level'), 'pipelines', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipelines_risk_level'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_pipeline_id'), table_name='pipelines')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
