"""add authority users and citizen contact fields

Revision ID: e5edf99b7e0b
Revises: 711ffa5fe8e2
Create Date: 2026-07-18 01:52:35.133609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5edf99b7e0b'
down_revision: Union[str, None] = '711ffa5fe8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authority_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authority_users_email'), 'authority_users', ['email'], unique=True)
    op.add_column('complaints', sa.Column('citizen_name', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'phone_number')
    op.drop_column('complaints', 'citizen_name')
    op.drop_index(op.f('ix_authority_users_email'), table_name='authority_users')
    op.drop_table('authority_users')
    # ### end Alembic commands ###
